# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TykOperator < Formula
  desc ""
  homepage "https://github.com/TykTechnologies/tyk-operator"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Keithwachira/tyk-operator/releases/download/v0.0.6/tyk-operator_0.0.6_Darwin_x86_64.tar.gz"
      sha256 "d7f8232b7355f5c439e8100dade1ab3e316b0affd669c22fff83ca7ca8792d86"

      def install
        bin.install "tyk-operator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Keithwachira/tyk-operator/releases/download/v0.0.6/tyk-operator_0.0.6_Darwin_arm64.tar.gz"
      sha256 "56df78dc4cc4e3d7fcf0eaa3008823b5acd8d1909ba40d9c3d5cb78bdf86c357"

      def install
        bin.install "tyk-operator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Keithwachira/tyk-operator/releases/download/v0.0.6/tyk-operator_0.0.6_Linux_arm64.tar.gz"
      sha256 "2e92f2a7daeb6f6b1a8b2ff9b96567d374d54ed54f67491872d514311a150a8d"

      def install
        bin.install "tyk-operator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Keithwachira/tyk-operator/releases/download/v0.0.6/tyk-operator_0.0.6_Linux_x86_64.tar.gz"
      sha256 "dfc677cfab4787424a89321f03c98a12690d330b7106df7ba5e063435b8c26fb"

      def install
        bin.install "tyk-operator"
      end
    end
  end
end
